### ISSUE TITLE
Local setup documentation

### ISSUE THREAD

**Issue by jayadeepreddy9** [akshayKMR/Biddu#1]
Devs would be needing local setup documentation without hosting on IBM blue mix.

**Comment by akshaykmr** [comment]
You'll need to install meteor tool https://www.meteor.com/install
To run the app l `meteor run` in the project root.  It should be available on `localhost:3000`

For social logins you'll need to replace appId and keys in `server/startup.js`. File upload to s3 also requires api key configuration in `sever/uploads.js`

**Comment by jayadeepreddy9** [comment]
Thanks Akshay,
I actually Did that I am getting the following error.  The homepage is
opening normally, But as soon I click on auctions I get the following
error. Not sure how to fix that.
MongoDB is working fine, Google auth is working, But failing on redirect
with the same error. I have also attached console



​
​

**Comment by akshaykmr** [comment]
It seems I didn't reply earlier because there wasn't any attachment. If anyone has a similar issue feel free to reopen.
